@startuml EnterExitActions

[*] --> StateA

State StateA : entry / EnterStateA
State StateA : exit / ExitStateA

StateA -> StateA : GoToAFromA
StateA -> StateB : GoToB
StateB -> StateA : GoToAFromB

' Composite state
state StateC {
  StateC: entry / EnterStateC
  StateC: exit / ExitStateC

  '  parent enter/exit are overwritten by substates
  State StateCA : entry / EnterStateCA
  State StateCA : exit / ExitStateCA

  [*] --> StateCA
  StateCA -> StateCB : GoToCB
}
StateA -> StateC : GoToC
StateA -> StateCA : GoToCAFromA
StateA -> StateCB : GoToCBFromA
StateC -> StateA : GoToAFromC

@enduml
