@startuml Composite States

state StateA {
    state StateAA {
        [*] --> StateAAA
        StateAAA --> StateAAB : GoToAAB / HandleGoToAAB
    }
    state StateAB

    [*] --> StateAA
    StateAA --> StateAB : GoToAB / HandleGoToAB
}

state StateB

[*] --> StateA
StateA --> StateB : GoToB / HandleGoToB

@enduml
