@startuml Substate To Substate
state StateA {
 'implicit definition of a substate'
  [*] --> StateAA
}

state StateB {
 'implicit definition of substates'
  StateBA --> StateBB: GoToBB / HandleGoToBB
}

[*] --> StateA
' substate to substate transition '
StateAA -> StateBA: GoToBA / HandleGoToBA
@enduml
