@startuml DirectTransitions
[*] --> StateA

StateA --> StateB : / ActionToB

StateB -> StateC : [CanGoToC] / ActionToC
StateB -> StateD : [CanGoToD]
StateB -> StateA: GoToA

state StateD: entry / EnterStateD

@enduml
