@startuml TestFsm

StateA -> StateA : SelfTransition / HandleSelfTransition
StateA -> StateB : GoToB / HandleGoToB
StateA -> StateB : GoToBDifferently / HandleGoToBDifferently
StateA -> StateC : GoToC
' Event lists cannot carry an action (one action binds to a single event's params)
StateB -> StateA : GoToA, GoToADifferently
[*] --> StateA

@enduml
